### ISSUE TITLE
gotchas within the blacktooth33 and blacktooth34 rooms

### ISSUE THREAD

**Issue by hendrikbez** [dougmencken/HeadOverHeels#65]
![Screenshot_3](https://github.com/dougmencken/HeadOverHeels/assets/49644474/fc8c2e5e-52c3-4f59-85bc-729608191a19)
When you fall from the room above, you loose al your life for falling down , as the enemy always go the same route to get to you, you can not do anything to escape the enemy

**Comment by dougmencken** [comment]
But how it goes in the original game 🤔? Heels can’t control itself on the fly....

Either way, it looks like this “imperial guard” hunter machine’s behavior needs to be modified to not see the character above it

**Comment by dougmencken** [comment]
okay now?
![don’t hunt if above.gif](https://github.com/dougmencken/HeadOverHeels/assets/3457110/e7f0476a-cd19-4969-9b61-9f4add800bad)

**Comment by hendrikbez** [comment]
Thank you,

Will play/test again later


*Jesus Christ is Lord*

*Not a swear word*

**Comment by dougmencken** [comment]
And yes, since you already asked about cheats... Such cases are the real reason to use them. For the situation mentioned, I’d suggest using **[ alt ] & [ shift ] & [ y ]** to become invulnerable for 25 seconds. [The list of cheat combinations of keys is published on the project’s wiki](https://github.com/dougmencken/HeadOverHeels/wiki/%E2%80%9C-Magic-%E2%80%9D-keys)

**Comment by dougmencken** [comment]
This is how that is at the current moment

![head-heels-falling](https://github.com/dougmencken/HeadOverHeels/assets/3457110/7063a82d-25fa-4f57-b7e4-79740a9b43dc)

**Comment by hendrikbez** [comment]
Thank you
Hendrik

**Comment by dougmencken** [comment]
falling down is accelerated now
since https://github.com/dougmencken/HeadOverHeels/commit/ab6baa66ab84c32ee335cfb3a240ab4bc25b9898

**Comment by dougmencken** [comment]
the `blacktooth33.xml` room is one of the hardest in this game

![Uploading that blacktooth33 room.gif…]()

**Comment by dougmencken** [comment]
...and once you passed it and went up, you meet that volatile brick in `blacktooth34.xml`

https://github.com/dougmencken/HeadOverHeels/blob/efeec5cc8695ef4d8851baaed3430570a37e99ef/gamedata/map/blacktooth34.xml#L88

meanwhile there’s also _"behavior of **slow** disappearance on jump into"_ which takes twenty (20) times longer before vanishing

https://github.com/dougmencken/HeadOverHeels/blob/efeec5cc8695ef4d8851baaed3430570a37e99ef/source/behaviors/Volatile.cpp#L12

**Comment by hendrikbez** [comment]
Thank you, will test it later today

**Comment by dougmencken** [comment]
after https://github.com/dougmencken/HeadOverHeels/commit/c2e66bbb109b20ba3cb3507e90ccdc83fe17759f and https://github.com/dougmencken/HeadOverHeels/commit/99ddae72191926bddcba1b93025710a1977e4dbb I think this issue is closed

**Comment by dougmencken** [comment]
![blacktooth-33-and-34-are-okay](https://github.com/dougmencken/HeadOverHeels/assets/3457110/7b30c0a2-fc51-42cf-91d1-a9c75e4573c0)

**Comment by hendrikbez** [comment]
What do you use to make a gif video in ubuntu, I need to make one to show
you a bug in a screen.  (I am new to linux)


*Jesus Christ is Lord*

*Not a swear word*

**Comment by dougmencken** [comment]
> What do you use to make a gif video in ubuntu, I need to make one to show you a bug in a screen. (I am new to linux)

_🤔 maybe add an article about it on the project’s wiki_

The videos I uploaded here are in fact GIF animations. At first I collect the sequence of in-game screen captures, that’s done by the game itself : to begin a recording hold [ alt ] [ shift ] and type [ v ], the same keys again will end the process. The recorded captures are put inside `~/.headoverheels/captures` and have names of some random sequence of 10 letters and digits and the sequence number of a frame. The file format of captures is PCX (because allegro library supports that)

Then I’m converting such a sequence of pictures into a GIF animation. I wrote how I do this in the recent 333rd commit https://github.com/dougmencken/HeadOverHeels/commit/efeec5cc8695ef4d8851baaed3430570a37e99ef (and sure you can find some other easier way to convert a bunch of PCXes into a GIF animation)

**Comment by dougmencken** [comment]
I’m closing this

**Comment by hendrikbez** [comment]
You can close it
